let suggestions = [
  "Rembrandt van Rijn",
  "Johannes Vermeer",
  "Vincent van Gogh",
  "Frans Hals",
  "Jan Steen",
  "Gerard Dou",
  "Jacob van Ruisdael",
  "Jan van Goyen",
  "Aert van der Neer",
  "Willem Kalf",
  "Jan Davidsz de Heem",
  "Abraham Mignon",
  "Adriaen Coorte",
  "Meindert Hobbema",
  "Salomon van Ruysdael",
  "Jan van Huysum",
  "Ambrosius Bosschaert",
  "Rachel Ruysch",
  "Peter Paul Rubens",
  "Anthony van Dyck",
  "Jacob Jordaens",
  "Frans Snyders",
  "Jan Brueghel the Elder",
  "Hendrick Avercamp",
  "Esaias van de Velde",
  "Isaac van Ostade",
  "Adriaen van Ostade",
  "David Teniers the Younger",
  "Albert Cuyp",
  "Jan Lievens",
  "Govert Flinck",
  "Jan Weenix",
  "Gabriel Metsu",
  "Bartholomeus van der Helst",
  "Gerrit Dou",
  "Pieter Lastman",
  "Jan Victors",
  "Jan Adam Kruseman",
  "Paulus Potter",
  "David Bailly",
  "Jacob Adriaensz Backer",
  "Pieter Bruegel the Elder",
  "Jan van Scorel",
  "Pieter Claesz",
  "Pieter de Hooch",
  "Jan van der Heyden",
  "Emanuel de Witte",
  "Cornelis Cornelisz. van Haarlem",
  "Lucas van Leyden",
  "Willem Buytewech",
  "Adam van Breen",
  "Jan van der Meer II",
  "Johannes Lingelbach",
  "Jan Baptist Weenix",
  "Balthasar van der Ast",
  "Hendrick ter Brugghen",
  "Jan Baptist Bosschaert",
  "Andries Beeckman",
  "Hendrick Goltzius",
  "Dirck van Baburen",
  "Gerrit van Honthorst",
  "Matthias Stom",
  "Hendrick Cornelisz. van Vliet",
  "Jan de Bray",
  "Pieter Jansz. Saenredam",
  "Gerard ter Borch",
  "Pieter Pietersz. Lastman",
  "Pieter Codde",
  "Joost Cornelisz. Droochsloot",
  "Jan Siberechts",
  "Willem van Aelst",
  "Jan van Kessel the Elder",
  "Nicolaes Berchem",
  "Philips Wouwerman",
  "Adriaen van de Velde",
  "Joachim Anthonisz. Wtewael",
  "Simon de Vlieger",
  "Willem van Mieris",
  "Willem van de Velde the Younger",
  "Nicolaes Maes",
  "Emanuel Murant",
  "Jan Baptist van der Hulst",
  "Frans van Mieris the Elder",
  "Adriaen van Utrecht",
  "Jan Wijnants",
  "Jan van de Velde II",
  "Hendrick van Balen",
  "Jan van Bijlert",
  "Jan Both",
  "Isaac Claesz. van Swanenburg",
  "Frans van de Wijngaerde",
  "The Night Watch",
  "The Milkmaid",
  "The Jewish Bride",
  "The Anatomy Lesson of Dr. Nicolaes Tulp",
  "The Merry Family",
  "The Windmill at Wijk bij Duurstede",
  "The Battle of Waterloo",
  "The Battle of Gibraltar",
  "The Adoration of the Shepherds",
  "Self-Portrait as the Apostle Paul",
  "The Threatened Swan",
  "A Cavalry Battle",
  "View of Delft",
  "Young Woman with a Water Pitcher",
  "The Laughing Cavalier",
  "Flower Still Life",
  "Aelbert Cuyp",
  "Danae",
  "Two Boys with a Bladder",
  "Still Life with Fruit",
  "Portrait of a Young Woman",
  "The Satyr and the Peasant",
  "The Baptism of Christ",
  "The Broken Earthenware",
  "Isaac and Rebecca",
  "The Peasant Dance",
  "Portrait of a Young Couple",
  "Still Life with Cheese",
  "Portrait of a Woman",
  "A Scholar Sharpening a Quill",
  "The Golden Bend",
  "Winter Landscape with Ice Skaters",
  "The Denial of St Peter",
  "Old Woman and Boy with Candle",
  "The Holy Family with a Curtain",
  "Vase with Flowers",
  "A View of Dordrecht",
  "An Old Woman Reading",
  "Still Life with Lobster",
  "The Duel Between Alexander Hamilton and Aaron Burr",
  "The Three Fates",
  "The Voyage of the ‘Emperor Maximilian’ to the West Indies",
  "The Merry Drinker",
  "The Beheading of Saint John the Baptist",
  "Bust of Louis XIV",
  "The Dam Square in Amsterdam",
  "Dune Landscape",
  "The Satyr and the Farmer's Family",
  "Portrait of Titus",
  "An Elegant Company Playing Music",
  "The Merry Lute Player",
  "The Nieuwezijds Chapel in Amsterdam",
  "The Meagre Company",
  "The Fruit Basket",
  "A Village Kermis with a Company Making Music",
  "The Great De Lairesse",
  "The Chess Players",
  "Portrait of a Young Woman",
  "Portrait of a Young Woman with a Fan",
  "The Andrians",
  "A Young Woman Standing at a Virginal",
  "The Bookkeeper",
  "The Four Evangelists",
  "The Fête Champêtre",
  "Landscape with a Ruin",
  "A Mother Delousing Her Child's Hair",
  "The Holy Family",
  "Baptismal Font from the Old Church at Delft",
  "Allegory of the Four Elements",
  "Landscape with the Castle of Francheville",
  "The Magdalen Reading",
  "The Siege of Haarlem",
  "Portrait of a Young Woman with a Feather Fan",
  "Portraits of Marten Soolmans and Oopjen Coppit",
  "Militia Company of District II under the Command of Captain Frans Banninck Cocq",
  "A Maid Milking a Cow in a Barn",
  "A Woman Holding a Balance",
  "The Rich Kitchen",
  "Portrait of Nicolaes Hasselaer",
  "Portrait of Jan Jacobsz. Hinlopen",
  "The Blue Jack",
  "A Winter Landscape",
  "The Conspiracy of Claudius Civilis",
  "Portrait of a Couple",
];

export default suggestions;
